### ISSUE TITLE
Trouble compiling the kernel

### ISSUE THREAD

**Issue by BNasmith** [gap-packages/Digraphs#323] opened 2020-06-04 01:32 UTC
Hello, I am having trouble compiling the kernel. I use a previous version of Digraphs on another device but I just installed GAP 4.11.0 on a Raspberry Pi 4B (8GB) and am having trouble getting Digraphs 1.1.1 to work. I use the command `./configure` in the digraphs folder and then I use `make`. Here is the output:
```
pi@raspberrypi:~/gap-4.11.0/pkg/digraphs-1.1.1 $ make
Making all in extern/edge-addition-planarity-suite-Version_3.0.0.5
make[1]: Entering directory '/home/pi/gap-4.11.0/pkg/digraphs-1.1.1/extern/edge-addition-planarity-suite-Version_3.0.0.5'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/pi/gap-4.11.0/pkg/digraphs-1.1.1/extern/edge-addition-planarity-suite-Version_3.0.0.5'
make[1]: Entering directory '/home/pi/gap-4.11.0/pkg/digraphs-1.1.1'
  CC       src/digraphs_la-digraphs.lo
gcc: error: unrecognized command line option ‘-mpopcnt’
make[1]: *** [Makefile:750: src/digraphs_la-digraphs.lo] Error 1
make[1]: Leaving directory '/home/pi/gap-4.11.0/pkg/digraphs-1.1.1'
make: *** [Makefile:931: all-recursive] Error 1
```
I don't know what to make of the error on the fourth-last line above. In any case, it seems that this is preventing me from loading digraphs in GAP. Here's what happens:
```
pi@raspberrypi:~/gap-4.11.0/pkg/digraphs-1.1.1 $ gap
 ┌───────┐   GAP 4.11.0 of 29-Feb-2020
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: armv7l-unknown-linux-gnueabihf-default32-kv7
 Configuration:  gmp 6.1.2, GASMAN, readline
 Loading the library and packages ...
 Packages:   AClib 1.3.2, Alnuth 3.1.2, AtlasRep 2.1.0, AutoDoc 2019.09.04, 
             AutPGrp 1.10.2, Browse 1.8.8, CaratInterface 2.3.3, CRISP 1.4.5, 
             Cryst 4.1.23, CrystCat 1.1.9, CTblLib 1.2.2, FactInt 1.6.3, 
             FGA 1.4.0, Forms 1.2.5, GAPDoc 1.6.3, genss 1.6.6, IO 4.7.0, 
             IRREDSOL 1.4, LAGUNA 3.9.3, orb 4.8.3, Polenta 1.3.9, 
             Polycyclic 2.15.1, PrimGrp 3.4.0, RadiRoot 2.8, recog 1.3.2, 
             ResClasses 4.7.2, SmallGrp 1.4.1, Sophus 1.24, SpinSym 1.5.2, 
             TomLib 1.2.9, TransGrp 2.0.5, utils 0.69
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> SetInfoLevel(InfoPackageLoading,4);
gap> LoadPackage("Digraphs");
#I  Digraphs: entering LoadPackage 
#I  Digraphs: PackageAvailabilityInfo for version 1.1.1
#I  Digraphs: the kernel module is not compiled, 
#I            the package cannot be loaded.
#I  Digraphs: PackageAvailabilityInfo: the AvailabilityTest function returned fail
#I  Digraphs: PackageAvailabilityInfo: no installed version fits
#I  Digraphs: return from LoadPackage, package is not available
fail
```
I'd appreciate any suggestions you might have.

**Comment by james-d-mitchell** [comment] 2020-06-04 08:31
Thanks for the report, this is, however a duplicate of Issue #320. In short, if you configure Digraphs using the flag `--without-intrinsics`, then everything should work ok:

~~~~
./configure --without-intrinsics && make
~~~~

I'll leave this issue open, in case you encounter any further issues, if note, could you let us know if everything works? Thanks!

**Comment by BNasmith** [comment] 2020-06-04 13:24
Thank you, unfortunately this fix didn't work for me. After running `./configure --without-intrinsics` followed by `make` I still get the same error:
```
pi@raspberrypi:~/gap-4.11.0/pkg/digraphs-1.1.1 $ make
Making all in extern/edge-addition-planarity-suite-Version_3.0.0.5
make[1]: Entering directory '/home/pi/gap-4.11.0/pkg/digraphs-1.1.1/extern/edge-addition-planarity-suite-Version_3.0.0.5'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/pi/gap-4.11.0/pkg/digraphs-1.1.1/extern/edge-addition-planarity-suite-Version_3.0.0.5'
make[1]: Entering directory '/home/pi/gap-4.11.0/pkg/digraphs-1.1.1'
  CC       src/digraphs_la-digraphs.lo
gcc: error: unrecognized command line option ‘-mpopcnt’
make[1]: *** [Makefile:750: src/digraphs_la-digraphs.lo] Error 1
make[1]: Leaving directory '/home/pi/gap-4.11.0/pkg/digraphs-1.1.1'
make: *** [Makefile:931: all-recursive] Error 1
```
Any ideas?

**Comment by BNasmith** [comment] 2020-06-04 14:49
I just tried that and it didn't seem to clear things up. I ran `make clean` and then I ran `./configure --without-intrinsics && make` again. It seems to give me the same error as before. I'm at a loss, not sure what to do.
```
make[1]: Entering directory '/home/pi/gap-4.11.0/pkg/digraphs-1.1.1'
  CC       src/digraphs_la-digraphs.lo
gcc: error: unrecognized command line option ‘-mpopcnt’
make[1]: *** [Makefile:750: src/digraphs_la-digraphs.lo] Error 1
make[1]: Leaving directory '/home/pi/gap-4.11.0/pkg/digraphs-1.1.1'
make: *** [Makefile:931: all-recursive] Error 1
pi@raspberrypi:~/gap-4.11.0/pkg/digraphs-1.1.1 $ gap
 ┌───────┐   GAP 4.11.0 of 29-Feb-2020
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: armv7l-unknown-linux-gnueabihf-default32-kv7
 Configuration:  gmp 6.1.2, GASMAN, readline
 Loading the library and packages ...
 Packages:   AClib 1.3.2, Alnuth 3.1.2, AtlasRep 2.1.0, AutoDoc 2019.09.04, 
             AutPGrp 1.10.2, Browse 1.8.8, CaratInterface 2.3.3, CRISP 1.4.5, 
             Cryst 4.1.23, CrystCat 1.1.9, CTblLib 1.2.2, FactInt 1.6.3, 
             FGA 1.4.0, Forms 1.2.5, GAPDoc 1.6.3, genss 1.6.6, IO 4.7.0, 
             IRREDSOL 1.4, LAGUNA 3.9.3, orb 4.8.3, Polenta 1.3.9, 
             Polycyclic 2.15.1, PrimGrp 3.4.0, RadiRoot 2.8, recog 1.3.2, 
             ResClasses 4.7.2, SmallGrp 1.4.1, Sophus 1.24, SpinSym 1.5.2, 
             TomLib 1.2.9, TransGrp 2.0.5, utils 0.69
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> LoadPackage("digraphs");
#I  Digraphs package is not available. To see further details, enter
#I  SetInfoLevel(InfoPackageLoading,4); and try to load the package again.
fail
gap> SetInfoLevel(InfoPackageLoading,4);
gap> LoadPackage("digraphs");
#I  Digraphs: entering LoadPackage 
#I  Digraphs: PackageAvailabilityInfo for version 1.1.1
#I  Digraphs: the kernel module is not compiled, 
#I            the package cannot be loaded.
#I  Digraphs: PackageAvailabilityInfo: the AvailabilityTest function returned fail
#I  Digraphs: PackageAvailabilityInfo: no installed version fits
#I  Digraphs: return from LoadPackage, package is not available
fail
```

**Comment by james-d-mitchell** [comment] 2020-06-17 17:33
I’m going to close this issue because it appears to be resolved.

**Closed by james-d-mitchell** 2020-06-17 17:33 UTC

**Comment by LemoUtan** [comment] 2021-02-25 00:38
Thanks for this. I had no idea what to do with the -mpopcnt flag in arm architectures.
Just a note, though, that digraphs-1.1.1 is still the one packaged up in the gap 4.11 distribution of Feb 2020.

**Comment by wilfwilson** [comment] 2021-02-25 09:34
Yes, that is a pity. The packages included with GAP distributions are not updated between releases of GAP, and unfortunately GAP releases have become less frequent in recent times.

Thankfully, last week at [GAP Days Spring 2021](https://www.gapdays.de/gapdays2021-spring/) a group of GAP contributors developed a new release system, which requires much less manual input than the previous one. This should lead to the release of 4.11.1 in the next week or so, with newer packages, and thereafter more frequent releases.
